<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.jasperbigsum-commits</groupId>
    <artifactId>generic-transfer-encrypt-parent</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <name>generic-transfer-encrypt-parent</name>

    <modules>
        <module>transfer-encrypt-core</module>
        <module>spring2-plugin</module>
        <module>spring3-plugin</module>
        <module>e2e-demo/server</module>
        <module>e2e-demo/server-spring3</module>
    </modules>
</project>
